// Data awal untuk seed. Setelah seed, sumber kebenaran adalah database —
// perubahan berikutnya dilakukan lewat halaman /admin, bukan file ini.
//
// Company: dipetakan dari array `data` di reference/mandiri-geomapping-cikini.html
//   reference.score  (high/med/low)  -> priority (HIGH/MED/LOW)
//   reference.credit (angka)         -> score
//   reference.kredit (Tinggi/...)    -> creditPotential
//   reference.status                 -> payrollStatus
// Merchant: koordinat dari Google Maps; status pembayaran, omzet, skor,
// prioritas & profil = isi SIMULASI.

import type { Prisma } from "../src/generated/prisma/client";

export const branchSeed: Prisma.BranchCreateInput = {
  name: "Bank Mandiri KCP Jakarta Taman Ismail Marzuki",
  address: "Jl. Cikini Raya No.34, Cikini, Menteng, Jakarta Pusat 10330",
  // TODO: koordinat perkiraan — verifikasi manual di Google Maps.
  lat: -6.1905,
  lng: 106.8386,
  radiusM: 2000,
};

type Seed = Prisma.EntityCreateInput;
type SeedNoType = Omit<Seed, "type">;

export const companySeed: Seed[] = ([
  { name: "PT Harmoni Dinamik Indonesia", category: "Kantor Korporat", icon: "building", address: "Jl. Probolinggo, Gondangdia", lat: -6.196479, lng: 106.839025, priority: "HIGH", score: 82, employeeEstimate: 450, payrollStatus: "BELUM_TERGARAP", creditPotential: "TINGGI", profile: "Kantor pusat korporat multi-lini (kesehatan & consumer wellness) di kawasan Gondangdia, menempati gedung kantor milik sendiri dengan skala karyawan tergolong besar untuk area Cikini." },
  { name: "Primaya Hospital PGI Cikini", category: "Rumah Sakit", icon: "hospital", address: "Jl. Raden Saleh Raya 40", lat: -6.191987, lng: 106.841935, priority: "HIGH", score: 88, employeeEstimate: 800, payrollStatus: "PROSPEK_HANGAT", creditPotential: "TINGGI", profile: "Rumah sakit umum swasta skala besar dalam jaringan Primaya Hospital, dengan volume pasien dan jumlah tenaga kerja termasuk yang tertinggi di kawasan Cikini." },
  { name: "Bunda General Hospital Jakarta", category: "Rumah Sakit", icon: "hospital", address: "Jl. Teuku Cik Ditiro 21", lat: -6.196022, lng: 106.837189, priority: "HIGH", score: 84, employeeEstimate: 600, payrollStatus: "BELUM_TERGARAP", creditPotential: "TINGGI", profile: "Rumah sakit umum swasta dengan layanan spesialis lengkap di kawasan Menteng, beroperasi 24 jam dengan jumlah staf medis & non-medis yang besar." },
  { name: "Hasjrat Abadi (HQ Toyota KTI)", category: "Distributor Otomotif", icon: "building", address: "Jl. RP. Soeroso 38", lat: -6.192056, lng: 106.835974, priority: "HIGH", score: 78, employeeEstimate: 350, payrollStatus: "EXISTING_BANK_LAIN", creditPotential: "SEDANG", profile: "Kantor pusat distributor utama Toyota untuk kawasan Indonesia Timur, entitas korporat mapan dengan histori bisnis panjang." },
  { name: "Menteng Mitra Afia Hospital", category: "Rumah Sakit", icon: "hospital", address: "Jl. Kalipasir 09", lat: -6.186967, lng: 106.838292, priority: "MED", score: 70, employeeEstimate: 300, payrollStatus: "BELUM_TERGARAP", creditPotential: "SEDANG", profile: "Rumah sakit swasta menengah dengan layanan rawat inap dan fisioterapi, beroperasi 24 jam." },
  { name: "STIKES PGI Cikini", category: "Institusi Pendidikan Kesehatan", icon: "edu", address: "Kompleks RS PGI Cikini", lat: -6.190553, lng: 106.841608, priority: "MED", score: 64, employeeEstimate: 150, payrollStatus: "BELUM_TERGARAP", creditPotential: "SEDANG", profile: "Institusi pendidikan tinggi kesehatan (keperawatan) yang menjadi bagian dari kompleks RS PGI Cikini, salah satu pionir pendidikan keperawatan di Indonesia." },
  { name: "PT Infrastruktur Bisnis Sejahtera", category: "Kantor Korporat (HQ)", icon: "building", address: "Jl. Cikini Raya 12-14", lat: -6.189072, lng: 106.837112, priority: "MED", score: 68, employeeEstimate: 220, payrollStatus: "PROSPEK_HANGAT", creditPotential: "SEDANG", profile: "Kantor pusat korporat penyedia layanan bisnis & infrastruktur, menempati gedung kantor milik sendiri di jalur utama Cikini Raya." },
  { name: "Biogreen Science Head Office", category: "Korporat / Training Center", icon: "building", address: "Jl. Cikini Raya 58Q", lat: -6.193799, lng: 106.838451, priority: "MED", score: 66, employeeEstimate: 180, payrollStatus: "BELUM_TERGARAP", creditPotential: "SEDANG", profile: "Kantor pusat sekaligus training center perusahaan produk kesehatan & kecantikan berjejaring." },
  { name: "PT Rapi Films", category: "Media & Produksi Film", icon: "media", address: "Jl. Cikini II No.7A", lat: -6.19107, lng: 106.836845, priority: "MED", score: 60, employeeEstimate: 120, payrollStatus: "BELUM_TERGARAP", creditPotential: "SEDANG", profile: "Salah satu rumah produksi film tertua di Indonesia, mengoperasikan kantor produksi dan distribusi di Cikini." },
  { name: "Gedung GKM (HQ Oxygen.id)", category: "Kantor Korporat / Retail Telco", icon: "building", address: "Jl. Cikini Raya 12", lat: -6.189066, lng: 106.837455, priority: "MED", score: 62, employeeEstimate: 140, payrollStatus: "PROSPEK_HANGAT", creditPotential: "SEDANG", profile: "Kantor pusat pemain retail telekomunikasi (Oxygen.id) dalam gedung perkantoran kecil di jalur CBD Cikini." },
  { name: "PT Intertek Utama Services", category: "Testing & Inspection (MNC)", icon: "building", address: "Jl. Cikini IV No.2", lat: -6.19284, lng: 106.838209, priority: "LOW", score: 58, employeeEstimate: 90, payrollStatus: "EXISTING_BANK_LAIN", creditPotential: "SEDANG", profile: "Kantor cabang perusahaan jasa inspeksi, pengujian, dan sertifikasi multinasional." },
  { name: "PT Karunia Berca Indonesia", category: "Software & Kontraktor", icon: "building", address: "Jl. Cikini Raya 95", lat: -6.194265, lng: 106.839772, priority: "LOW", score: 48, employeeEstimate: 60, payrollStatus: "BELUM_TERGARAP", creditPotential: "RENDAH", profile: "Perusahaan kontraktor dan pengembang software skala kecil-menengah." },
] satisfies SeedNoType[]).map((c) => ({ ...c, type: "COMPANY" as const }));

export const merchantSeed: Seed[] = ([
  // Klaster emas — prioritas tinggi
  { name: "Cikini Gold Center", category: "Pusat Perhiasan Emas", icon: "gold", address: "Jl. Pegangsaan Timur 9", lat: -6.1981867, lng: 106.8416725, priority: "HIGH", score: 90, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "TINGGI", productFit: "EDC, Livin' Merchant, Tabungan Emas, KUR", profile: "Sentra toko emas & perhiasan dengan puluhan tenant dan nilai transaksi per tiket yang tinggi — kandidat utama akuisisi EDC dan pembiayaan modal kerja pedagang." },
  { name: "Toko Emas Cikini", category: "Toko Emas", icon: "gold", address: "Cikini Gold Center, Jl. Pegangsaan Timur 9", lat: -6.1980084, lng: 106.8418319, priority: "HIGH", score: 86, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "TINGGI", productFit: "EDC, Livin' Merchant, KUR", profile: "Toko emas di dalam Cikini Gold Center dengan perputaran transaksi tunai & kartu yang besar; titik masuk untuk menggarap tenant lain di gedung yang sama." },
  { name: "Pasar Cikini", category: "Pasar Tradisional", icon: "retail", address: "Jl. Pegangsaan Timur", lat: -6.1982347, lng: 106.8412812, priority: "HIGH", score: 84, paymentStatus: "BELUM_ADA", turnoverEstimate: "TINGGI", productFit: "Livin' Merchant (QRIS), KUR, Tabungan", profile: "Pasar tradisional yang menyatu dengan klaster emas Pegangsaan Timur; banyak pedagang masih bertransaksi tunai sehingga potensi onboarding QRIS & KUR mikro besar." },
  { name: "Yuli Mart", category: "Minimarket Independen", icon: "retail", address: "Jl. Cikini Raya 81", lat: -6.1923836, lng: 106.8389778, priority: "HIGH", score: 74, paymentStatus: "BELUM_ADA", turnoverEstimate: "SEDANG", productFit: "Livin' Merchant (QRIS), EDC, KUR", profile: "Minimarket non-jaringan di jalur utama Cikini Raya, sangat dekat dengan cabang; keputusan pemilik bisa diambil langsung sehingga siklus akuisisi pendek." },
  { name: "Jakarta Fruit Market", category: "Toko Buah & Grocery", icon: "retail", address: "Jl. Raden Saleh Raya 52", lat: -6.1927425, lng: 106.840717, priority: "MED", score: 70, paymentStatus: "QRIS_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "Livin' Merchant, EDC", profile: "Toko buah & grocery dengan pelanggan rumah tangga dan karyawan RS di sekitar Raden Saleh; sudah menerima QRIS bank lain." },
  { name: "LUC Coffee Menteng", category: "Coffee Shop", icon: "food", address: "Jl. Teuku Cik Ditiro 3", lat: -6.1942379, lng: 106.8367155, priority: "MED", score: 68, paymentStatus: "QRIS_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "Livin' Merchant, EDC", profile: "Coffee shop di kawasan Menteng dengan pengunjung pekerja kantoran & mahasiswa; transaksi didominasi pembayaran non-tunai." },
  { name: "The Banjoemas Resto & Cafe", category: "Restoran & Kafe", icon: "food", address: "Jl. Cikini Raya 8", lat: -6.1906316, lng: 106.838306, priority: "MED", score: 66, paymentStatus: "QRIS_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "Livin' Merchant, EDC", profile: "Restoran & kafe dengan menu khas Banyumasan tepat di sebelah cabang; ramai saat jam makan siang karyawan sekitar Cikini." },
  { name: "D Arabicah Restaurant", category: "Restoran Timur Tengah", icon: "food", address: "Jl. Cikini Raya 86", lat: -6.1959378, lng: 106.8396376, priority: "MED", score: 64, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "EDC, Livin' Merchant", profile: "Restoran masakan Timur Tengah dengan pelanggan keluarga & rombongan; nilai tiket rata-rata relatif tinggi." },
  { name: "TSNADA Jakarta", category: "Jazz Cafe & Live Music", icon: "food", address: "Jl. Cikini Raya 37", lat: -6.1880489, lng: 106.8370379, priority: "MED", score: 62, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "EDC, Livin' Merchant", profile: "Jazz cafe dengan live music malam hari, berdekatan dengan kawasan seni TIM; transaksi terkonsentrasi di malam & akhir pekan." },
  { name: "Artland Menteng (Menteng Huis)", category: "Pusat Belanja Kecil", icon: "retail", address: "Jl. Cikini Raya 2-4", lat: -6.188075, lng: 106.836416, priority: "MED", score: 58, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "EDC, Livin' Merchant", profile: "Gedung bersejarah Menteng Huis berisi tenant ritel & kuliner; pendekatan bisa per tenant maupun lewat pengelola gedung." },
  { name: "Kedai Sesama Cikini", category: "Kedai Kopi", icon: "food", address: "Jl. Raden Saleh Raya 27", lat: -6.1916149, lng: 106.8427501, priority: "LOW", score: 54, paymentStatus: "QRIS_BANK_LAIN", turnoverEstimate: "RENDAH", productFit: "Livin' Merchant (QRIS)", profile: "Kedai kopi komunitas skala kecil di Raden Saleh; volume transaksi terbatas namun loyalitas pelanggan tinggi." },
  { name: "De'kafe (Mercure Cikini)", category: "Kafe Hotel", icon: "food", address: "Jl. Cikini Raya 66 (Hotel Mercure)", lat: -6.1941766, lng: 106.8391966, priority: "LOW", score: 46, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "SEDANG", productFit: "EDC", profile: "Kafe di dalam hotel jaringan internasional; kebijakan acquiring kemungkinan diputuskan di level grup hotel, bukan outlet." },
  { name: "Hero Gondangdia", category: "Supermarket Jaringan", icon: "retail", address: "Jl. RP. Soeroso 30", lat: -6.1905168, lng: 106.8357878, priority: "LOW", score: 42, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "TINGGI", productFit: "Payroll karyawan outlet, EDC", profile: "Supermarket jaringan nasional; omzet tinggi tetapi acquiring diatur di kantor pusat — peluang cabang lebih pada karyawan outlet." },
  // Anchor — di tepi radius, kemungkinan dipegang level korporat
  { name: "Sarinah", category: "Department Store / Mal", icon: "mall", address: "Jl. M.H. Thamrin 11", lat: -6.1873954, lng: 106.8238375, priority: "LOW", score: 50, isAnchor: true, paymentStatus: "SUDAH_MANDIRI", turnoverEstimate: "TINGGI", productFit: "Livin' Merchant untuk tenant UMKM, EDC", profile: "Pusat belanja ikonik milik BUMN di Thamrin dengan banyak tenant produk lokal; relasi utama kemungkinan di level korporat, cabang dapat menggarap tenant UMKM." },
  { name: "Plaza Indonesia", category: "Mal Premium", icon: "mall", address: "Jl. M.H. Thamrin 28-30", lat: -6.1935977, lng: 106.8219468, priority: "LOW", score: 48, isAnchor: true, paymentStatus: "EDC_BANK_LAIN", turnoverEstimate: "TINGGI", productFit: "EDC tenant, Livin' Merchant", profile: "Mal premium di tepi radius 2 km; kerja sama acquiring kemungkinan ditangani level korporat/wilayah — cocok sebagai referensi, bukan target utama cabang." },
] satisfies SeedNoType[]).map((m) => ({ ...m, type: "MERCHANT" as const }));
